# Generated by Django 4.2.7 on 2024-01-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_categories_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categorie',
            new_name='category',
        ),
    ]
