# Generated by Django 4.2.7 on 2024-01-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_rename_categorie_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'товар', 'verbose_name_plural': 'товари'},
        ),
    ]
